# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'person_info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(703, 553)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 381, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBoxAge = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBoxAge.setObjectName("spinBoxAge")
        self.gridLayout.addWidget(self.spinBoxAge, 3, 1, 1, 1)
        self.lbl_age = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_age.setObjectName("lbl_age")
        self.gridLayout.addWidget(self.lbl_age, 3, 0, 1, 1)
        self.lineEdit_surname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.gridLayout.addWidget(self.lineEdit_surname, 2, 1, 1, 1)
        self.lbl_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout.addWidget(self.lbl_name, 0, 0, 1, 1)
        self.lbl_surname = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_surname.setObjectName("lbl_surname")
        self.gridLayout.addWidget(self.lbl_surname, 2, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 240, 641, 251))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.gridLayoutWidget_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_2.addWidget(self.calendarWidget, 2, 0, 1, 1)
        self.lbl_year = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_year.setObjectName("lbl_year")
        self.gridLayout_2.addWidget(self.lbl_year, 0, 0, 1, 1)
        self.plainTextEditInfo = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEditInfo.setObjectName("plainTextEditInfo")
        self.gridLayout_2.addWidget(self.plainTextEditInfo, 2, 1, 1, 1)
        self.lbl_info = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbl_info.setObjectName("lbl_info")
        self.gridLayout_2.addWidget(self.lbl_info, 0, 1, 1, 1)
        self.lbl_photo = QtWidgets.QLabel(Form)
        self.lbl_photo.setGeometry(QtCore.QRect(440, 20, 221, 171))
        self.lbl_photo.setObjectName("lbl_photo")
        self.btn_addPhoto = QtWidgets.QPushButton(Form)
        self.btn_addPhoto.setGeometry(QtCore.QRect(484, 210, 171, 23))
        self.btn_addPhoto.setObjectName("btn_addPhoto")
        self.bth_addPerson_done = QtWidgets.QPushButton(Form)
        self.bth_addPerson_done.setGeometry(QtCore.QRect(20, 510, 211, 23))
        self.bth_addPerson_done.setObjectName("bth_addPerson_done")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_age.setText(_translate("Form", "Возраст"))
        self.lbl_name.setText(_translate("Form", "Имя: "))
        self.lbl_surname.setText(_translate("Form", "Фамилия: "))
        self.lbl_year.setText(_translate("Form", "Дата рождения: "))
        self.lbl_info.setText(_translate("Form", "Информация: "))
        self.lbl_photo.setText(_translate("Form", " "))
        self.btn_addPhoto.setText(_translate("Form", "Добавить фото"))
        self.bth_addPerson_done.setText(_translate("Form", "Ок"))
